### ISSUE TITLE
0.5.0-PRERELEASE-20191209002126 failing on launch.

### ISSUE THREAD

**Issue by bareheiny** [comixed/comixed#95]
CX is currently failing on a Windows 10 machine

The previous pre-release build ran with no issues.  Refer to the attached log file for the CMD window.

[CX error.txt](https://github.com/comixed/comixed/files/3938372/CX.error.txt)

**Comment by mcpierce** [comment]
Hrm, so it seems that the ${HOME} placeholder's not defined in the Windows VM as it is on *nix systems.

I've pushed a fix for this, and should be available in the next prerelease build. Please let me know if it works.

**Comment by bareheiny** [comment]
Unfortunately CX still won't start.

This time I started CX using the run.bat file - with no parameters, and no existing database.

[CX error.txt](https://github.com/comixed/comixed/files/3941770/CX.error.txt)

**Comment by mcpierce** [comment]
@bareheiny I'm not sure what's going on there. I'm seeing this in the log you posted:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'detailsController': Unsatisfied dependency expressed through field 'detailsService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'detailsService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'HOME' in value "[Issue #95] Replace ${HOME} with ${user.home} for the cache directory."
```

It's trying to process a git commit message, which doesn't show up anywhere in the zipfile at all. Are you in the bin directory created by the archive when you opened it? I downloaded the zip and was able to launch it from the bin directory on my Windows machine without any problems.

**Comment by bareheiny** [comment]
I did think the error message looked odd.

I just re-downloaded prerelease-20191209133734, and extracted it to the root of a empty drive.  Navigated to comixed-app-0.5.0-PRERELEASE\bin and double cliked run.bat - no luck, still fails.

I also ran the bat from a cmd line (again, navigating to the the bin directory first) with the same result.

**Comment by mcpierce** [comment]
What happens if from the command line you just do:

java -jar [JARFILE]
-- 
Sent from Gmail Mobile

**Comment by bareheiny** [comment]
Same thing.  Not unexpected I would hope.

**Comment by mcpierce** [comment]
I’m not sure then what’s going on. I haven’t been able to reproduce what
you’re seeing with the same build file. I’ll keep trying.
-- 
Sent from Gmail Mobile

**Comment by bareheiny** [comment]
All good - I'm reinstalling IntelliJ, so will clone and compile a copy on my machine and see what happens.

**Comment by bareheiny** [comment]
Cloned and compliled, and still getting the same issue.

As you mentioned, there is no trace of "[Issue #95]" in the code either.


Bit more info (just in case):

64-bit Windows 10 Pro (on a Surface Pro and a desktop).
Java version "1.8.0_231" on the Surface, not sure of the desktop....likely similar.

**Comment by jmcrfp** [comment]
I was able to replicate.
Your @mcpierce commit fixed the first issue, but created a similar issue.
The Git-Commit-plugin generated a build-details.properties with the commit message that has the variable place holder again, and spring tries to replace it again. 

[build-details.zip](https://github.com/comixed/comixed/files/3944461/build-details.zip)

"Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'HOME' in value "[Issue #95] Replace ${HOME} with ${user.home} for the cache directory." at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172) at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)"

So just do another commit with a different commit message and the new build should be fine.

**Comment by mcpierce** [comment]
@jmcrfp Ah, thanks for that! I've fixed #81 and pushed that change this morning.

@bareheiny Please check if that fixes things for you when the release is created.

**Comment by bareheiny** [comment]
Looks good - CX is now starting.

**Comment by bareheiny** [comment]
All working now - although cx didn’t like my existing dB.

It threw some sort of jdbc erroe after a while, was really slow to load and wasn’t creating the cover caches.

Started fresh - and things look promising based on the initial load of 10 comics.
